name: MET API CD


on:
  push:
    branches:
      - main
    paths:
      - "met-api/**"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (dev/test/prod)"
        required: true
        default: "dev"     

defaults:
  run:
    shell: bash
    working-directory: ./met-api

env:
  APP_NAME: "met-api"
  TAG_NAME: "${{ github.event.inputs.environment || 'dev' }}"
  OPENSHIFT_LOGIN_REGISTRY: ${{ secrets.OPENSHIFT_LOGIN_REGISTRY }}
  OPENSHIFT_SA_TOKEN: ${{ secrets.OPENSHIFT_SA_TOKEN_EAO }}
  OPENSHIFT_SA_NAME: ${{ secrets.OPENSHIFT_SA_NAME_EAO }}
  OPENSHIFT_IMAGE_REGISTRY: ${{ secrets.OPENSHIFT_IMAGE_REGISTRY_EAO }}
  OPENSHIFT_REPOSITORY: ${{ secrets.OPENSHIFT_REPOSITORY_EAO }}
  
  
jobs:
  met-api-cd:
    runs-on: ubuntu-latest

    if: github.repository == 'bcgov/epic-engage'
    environment:
      name: "dev"

    steps:
      - uses: actions/checkout@v2

      - name: Install OpenShift CLI
        run: |
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz"
          tar -xvzf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/
          rm -f openshift-client-linux.tar.gz

      - name: Login Openshift
        shell: bash
        run: |
          oc login --server=${{env.OPENSHIFT_LOGIN_REGISTRY}} --token=${{env.OPENSHIFT_SA_TOKEN}}

      - name: Login Docker
        run: |
          echo "${{ env.OPENSHIFT_SA_TOKEN }}" | 
          docker login ${{ env.OPENSHIFT_IMAGE_REGISTRY }} -u ${{ env.OPENSHIFT_SA_NAME}} --password-stdin

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag image

      - name: Push image
        run: |
          IMAGE_ID=${{ env.OPENSHIFT_IMAGE_REGISTRY }}/"${{ env.OPENSHIFT_REPOSITORY}}-tools"/$APP_NAME
          docker tag image $IMAGE_ID:$TAG_NAME
          docker push $IMAGE_ID:$TAG_NAME

      - name: Rollout
        shell: bash
        run: |
          oc rollout status dc/${{ env.APP_NAME }} -n ${{ env.OPENSHIFT_REPOSITORY }}-${{ env.TAG_NAME }} -w
